### ISSUE TITLE
main.CRITICAL: Error: Call to a member function get() on null in

### ISSUE THREAD

**Issue by antrax131** [MagestioEcommerce/redsys-tpv#27]
Hola,
He actualizado a Magento 2.4.3 -p2 desde Magento 2.4.3 -p1 y no finaliza las compras, error:

Pantalla en blanco y "An error has happened during application run. See exception log for details." 

Error en system log:

`[2022-04-19 17:44:38] main.CRITICAL: Error: Call to a member function get() on null in /var/www/vhosts/XXXXXXXX.com/httpdocs/vendor/magento/framework/App/Action/Action.php:109
Stack trace:
#0 /var/www/vhosts/XXXXXXXX.com/httpdocs/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Framework\App\Action\Action->dispatch()
#1 /var/www/vhosts/XXXXXXXX.com/httpdocs/vendor/magento/framework/Interception/Interceptor.php(138): Magestio\Redsys\Controller\Redirect\Index\Interceptor->___callParent()
#2 /var/www/vhosts/XXXXXXXX.com/httpdocs/vendor/magento/framework/Interception/Interceptor.php(153): Magestio\Redsys\Controller\Redirect\Index\Interceptor->Magento\Framework\Interception\{closure}()
#3 /var/www/vhosts/XXXXXXXX.com/httpdocs/generated/code/Magestio/Redsys/Controller/Redirect/Index/Interceptor.php(32): Magestio\Redsys\Controller\Redirect\Index\Interceptor->___callPlugins()
#4 /var/www/vhosts/XXXXXXXX.com/httpdocs/vendor/magento/framework/App/FrontController.php(245): Magestio\Redsys\Controller\Redirect\Index\Interceptor->dispatch()
#5 /var/www/vhosts/XXXXXXXX.com/httpdocs/vendor/magento/framework/App/FrontController.php(212): Magento\Framework\App\FrontController->getActionResponse()
#6 /var/www/vhosts/XXXXXXXX.com/httpdocs/vendor/magento/framework/App/FrontController.php(147): Magento\Framework\App\FrontController->processRequest()
#7 /var/www/vhosts/XXXXXXXX.com/httpdocs/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Framework\App\FrontController->dispatch()
#8 /var/www/vhosts/XXXXXXXX.com/httpdocs/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\App\FrontController\Interceptor->___callParent()
#9 /var/www/vhosts/XXXXXXXX.com/httpdocs/vendor/magento/module-store/App/FrontController/Plugin/RequestPreprocessor.php(99): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}()
#10 /var/www/vhosts/XXXXXXXX.com/httpdocs/vendor/magento/framework/Interception/Interceptor.php(135): Magento\Store\App\FrontController\Plugin\RequestPreprocessor->aroundDispatch()
#11 /var/www/vhosts/XXXXXXXX.com/httpdocs/vendor/magento/module-page-cache/Model/App/FrontController/BuiltinPlugin.php(75): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}()
#12 /var/www/vhosts/XXXXXXXX.com/httpdocs/vendor/magento/framework/Interception/Interceptor.php(135): Magento\PageCache\Model\App\FrontController\BuiltinPlugin->aroundDispatch()
#13 /var/www/vhosts/XXXXXXXX.com/httpdocs/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}()
#14 /var/www/vhosts/XXXXXXXX.com/httpdocs/generated/code/Magento/Framework/App/FrontController/Interceptor.php(23): Magento\Framework\App\FrontController\Interceptor->___callPlugins()
#15 /var/www/vhosts/XXXXXXXX.com/httpdocs/vendor/magento/framework/App/Http.php(116): Magento\Framework\App\FrontController\Interceptor->dispatch()
#16 /var/www/vhosts/XXXXXXXX.com/httpdocs/vendor/magento/framework/App/Bootstrap.php(264): Magento\Framework\App\Http->launch()
#17 /var/www/vhosts/XXXXXXXX.com/httpdocs/pub/index.php(29): Magento\Framework\App\Bootstrap->run()
#18 {main} [] []`

**Comment by antrax131** [comment]
Solucionado.
