### ISSUE TITLE
Error conectando con redsys

### ISSUE THREAD

**Issue by antrax131** [MagestioEcommerce/redsys-tpv#28]
Hola,

He actualizado a Magento 2.4.3-p2 Y es imposible conectar se queda en esta url https://XXXXX.com/es/redsys/redirect/?gateway=redsys y con Redsys error:

Redireccionando al TPV de Redsys. Por favor espere.

Gracias por confiar en nosotros En unos segundos, se le redirigirá a la plataforma de pago.

Si su navegador no le redirige automáticamente, haga click [aquí](javascript:void(0)) para continuar con el pago.

He probado los diferentes branches de paugnu sin con el misnmo problema,  96f1c2d on 7 May 2021 es el que tengo instalado y veo que es compatible con magento 2.4

¿Alguien sabe como resolverlo?

**Comment by antrax131** [comment]
Se me olvido comentar si instalo la version master con el commit 645da22 el error es 

An error has happened during application run. See exception log for details.

`[2022-06-28 14:48:55] main.CRITICAL: Error: Call to a member function get() on null in /var/www/vhosts/lolatoys.com/httpdocs/vendor/magento/framework/App/Action/Action.php:109
Stack trace:
#0 /var/www/vhosts/lolatoys.com/httpdocs/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Framework\App\Action\Action->dispatch()
#1 /var/www/vhosts/lolatoys.com/httpdocs/vendor/magento/framework/Interception/Interceptor.php(138): Magestio\Redsys\Controller\Redirect\Index\Interceptor->___callParent()
#2 /var/www/vhosts/lolatoys.com/httpdocs/vendor/magento/framework/Interception/Interceptor.php(153): Magestio\Redsys\Controller\Redirect\Index\Interceptor->Magento\Framework\Interception\{closure}()
#3 /var/www/vhosts/lolatoys.com/httpdocs/generated/code/Magestio/Redsys/Controller/Redirect/Index/Interceptor.php(32): Magestio\Redsys\Controller\Redirect\Index\Interceptor->___callPlugins()
#4 /var/www/vhosts/lolatoys.com/httpdocs/vendor/magento/framework/App/FrontController.php(245): Magestio\Redsys\Controller\Redirect\Index\Interceptor->dispatch()
#5 /var/www/vhosts/lolatoys.com/httpdocs/vendor/magento/framework/App/FrontController.php(212): Magento\Framework\App\FrontController->getActionResponse()
#6 /var/www/vhosts/lolatoys.com/httpdocs/vendor/magento/framework/App/FrontController.php(147): Magento\Framework\App\FrontController->processRequest()
#7 /var/www/vhosts/lolatoys.com/httpdocs/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Framework\App\FrontController->dispatch()
#8 /var/www/vhosts/lolatoys.com/httpdocs/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\App\FrontController\Interceptor->___callParent()
#9 /var/www/vhosts/lolatoys.com/httpdocs/vendor/magento/module-store/App/FrontController/Plugin/RequestPreprocessor.php(99): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}()
#10 /var/www/vhosts/lolatoys.com/httpdocs/vendor/magento/framework/Interception/Interceptor.php(135): Magento\Store\App\FrontController\Plugin\RequestPreprocessor->aroundDispatch()
#11 /var/www/vhosts/lolatoys.com/httpdocs/vendor/magento/module-page-cache/Model/App/FrontController/BuiltinPlugin.php(75): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}()
#12 /var/www/vhosts/lolatoys.com/httpdocs/vendor/magento/framework/Interception/Interceptor.php(135): Magento\PageCache\Model\App\FrontController\BuiltinPlugin->aroundDispatch()
#13 /var/www/vhosts/lolatoys.com/httpdocs/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}()
#14 /var/www/vhosts/lolatoys.com/httpdocs/generated/code/Magento/Framework/App/FrontController/Interceptor.php(23): Magento\Framework\App\FrontController\Interceptor->___callPlugins()
#15 /var/www/vhosts/lolatoys.com/httpdocs/vendor/magento/framework/App/Http.php(116): Magento\Framework\App\FrontController\Interceptor->dispatch()
#16 /var/www/vhosts/lolatoys.com/httpdocs/vendor/magento/framework/App/Bootstrap.php(264): Magento\Framework\App\Http->launch()
#17 /var/www/vhosts/lolatoys.com/httpdocs/pub/index.php(29): Magento\Framework\App\Bootstrap->run()
#18 {main} [] []
`

**Comment by anton-vidext** [comment]
Mismo error con la última versión del módulo y Magento 2.4.4

```
[2022-10-17T08:50:52.167906+00:00] main.CRITICAL: Error: Call to a member function get() on null in /home/pickaudi/public_html/vendor/magento/framework/App/Action/Action.php:109
Stack trace:
#0 /home/pickaudi/public_html/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Framework\App\Action\Action->dispatch(Object(Magento\Framework\App\Request\Http))
#1 /home/pickaudi/public_html/vendor/magento/framework/Interception/Interceptor.php(138): Magestio\Redsys\Controller\Redirect\Index\Interceptor->___callParent('dispatch', Array)
#2 /home/pickaudi/public_html/vendor/magento/framework/Interception/Interceptor.php(153): Magestio\Redsys\Controller\Redirect\Index\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#3 /home/pickaudi/public_html/generated/code/Magestio/Redsys/Controller/Redirect/Index/Interceptor.php(32): Magestio\Redsys\Controller\Redirect\Index\Interceptor->___callPlugins('dispatch', Array, Array)
#4 /home/pickaudi/public_html/vendor/magento/framework/App/FrontController.php(245): Magestio\Redsys\Controller\Redirect\Index\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#5 /home/pickaudi/public_html/vendor/magento/framework/App/FrontController.php(212): Magento\Framework\App\FrontController->getActionResponse(Object(Magestio\Redsys\Controller\Redirect\Index\Interceptor), Object(Magento\Framework\App\Request\Http))
#6 /home/pickaudi/public_html/vendor/magento/framework/App/FrontController.php(147): Magento\Framework\App\FrontController->processRequest(Object(Magento\Framework\App\Request\Http), Object(Magestio\Redsys\Controller\Redirect\Index\Interceptor))
#7 /home/pickaudi/public_html/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Framework\App\FrontController->dispatch(Object(Magento\Framework\App\Request\Http))
#8 /home/pickaudi/public_html/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\App\FrontController\Interceptor->___callParent('dispatch', Array)
#9 /home/pickaudi/public_html/vendor/magento/module-store/App/FrontController/Plugin/RequestPreprocessor.php(99): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#10 /home/pickaudi/public_html/vendor/magento/framework/Interception/Interceptor.php(135): Magento\Store\App\FrontController\Plugin\RequestPreprocessor->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#11 /home/pickaudi/public_html/vendor/magento/module-page-cache/Model/App/FrontController/BuiltinPlugin.php(75): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#12 /home/pickaudi/public_html/vendor/magento/framework/Interception/Interceptor.php(135): Magento\PageCache\Model\App\FrontController\BuiltinPlugin->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#13 /home/pickaudi/public_html/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#14 /home/pickaudi/public_html/generated/code/Magento/Framework/App/FrontController/Interceptor.php(23): Magento\Framework\App\FrontController\Interceptor->___callPlugins('dispatch', Array, NULL)
#15 /home/pickaudi/public_html/vendor/magento/framework/App/Http.php(116): Magento\Framework\App\FrontController\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#16 /home/pickaudi/public_html/generated/code/Magento/Framework/App/Http/Interceptor.php(23): Magento\Framework\App\Http->launch()
#17 /home/pickaudi/public_html/vendor/magento/framework/App/Bootstrap.php(264): Magento\Framework\App\Http\Interceptor->launch()
#18 /home/pickaudi/public_html/pub/index.php(30): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http\Interceptor))
```

**Comment by xdosil** [comment]
Hola. Mismo error en una versión 2.4.3-p2. Alguna solución al problema? Saludos!
